### ISSUE TITLE
Create a report File

### ISSUE THREAD

**Issue by yvkrishna** [flow2ml/Flow2ML#51] opened 2021-04-21 10:46 UTC
You will be having the result metrics like confusion matrix, roc curves, etc in a folder.
As part of this issue, one needs to figure out a solution to generate a report.pdf file that contains the following information.

1. Accuracy-Loss plots,
2. Confusion Matrix,
3. Roc Curves

**Comment by Trisanu-007** [comment] 2021-04-25 15:16
Is this issue taken? If not can it be assigned to me ?

**Comment by yvkrishna** [comment] 2021-04-26 08:24
okay

**Comment by Trisanu-007** [comment] 2021-04-27 16:36
@yvkrishna can you provide some more clarity on this issue, particularly on the result metrics and if possible with an example?

**Comment by yvkrishna** [comment] 2021-04-29 05:29
@Trisanu-007, once the #50 issue is resolved then we can expect a folder created inside dataset_dir named as results. In that folder, we would have confusion matrix, ROC curves, Accuracy plots, etc which would be given as input by the user. 

Now as part of this issue, you would deal with the results folder. You need to assume that there is a confusion matrix, roc curves and accuracy plots inside the results folder. Considering those plots as images you are expected to create a pdf file describing the trained model. 

For Example, If a user trains a dataset with result metrics as Accuracy, Confusion matrix, Roc Curves, then you need to put those plots as images in the report.pdf file.

**Comment by chebroluharika** [comment] 2021-05-01 12:44
@yvkrishna Is this duplicate of #44. If not. please make me understand what makes them different to each other

**Comment by yvkrishna** [comment] 2021-05-02 03:14
I thought #44 is a big issue so I thought of splitting the work into parts and created 2 issues, this is one among them.

**Comment by chebroluharika** [comment] 2021-05-02 08:51
@yvkrishna  @Trisanu-007 I think this is addressed as a part of https://github.com/flow2ml/Flow2ML/pull/69/files

**Comment by chebroluharika** [comment] 2021-05-02 08:53
Hence, closing this. Please feel free to reopen if you find any issues.

**Closed** 2021-05-02 08:53 UTC
Labels: enhancement, gssoc21, level2
