### ISSUE TITLE
Update Readme File

### ISSUE THREAD

**Issue by jyoti-anjaly** [flow2ml/Flow2ML#12] opened 2021-03-11 13:49 UTC
Hey, I am GSSOC'21 Participant.
I would like to update the readme file by adding some contents like "How to contribute" and "How to make pull request".
Can to please assign this to me?

**Comment by ANAMIKA1410** [comment] 2021-03-12 11:02
Hey, I am Anamika, a GSSOC'21 Participant.
I would like contribute in this project and wants to update the readme file by adding some contents like "How to contribute" and "How to make pull request" and "by writing about the projects intro".

please assign this to me

**Comment by yvkrishna** [comment] 2021-03-12 11:12
@jyoti-anjaly @ANAMIKA1410  updating the readme and accepting it may take some time because that decision has to be taken by the group of mentors and myself. we need to review a lot and also the project period has just started. 

You can create a file for contributing.md and state your views on it and we would see that. The readme contains the main introduction and main documentation so updating it may take some time.

Thank you for asking.
Vedha Krishna :slightly_smiling_face:

**Comment by yvkrishna** [comment] 2021-03-12 11:39
Also when the time comes the team would announce changes for readme in this issue, so you can start working at that time.

**Comment by Elizah550** [comment] 2021-03-16 08:30
Heyy !!
I am participant too but assure you that I can do this issue in the best possible way please assign it to me. 
Thanks !!!

**Comment by Sibasish-Padhy** [comment] 2021-03-21 11:17
@yvkrishna can i contribute to this isue under the label of gssoc'21

**Comment by Dhriti-Roy** [comment] 2021-03-21 14:27
I am a Gssoc'21 participant , I would like to work on it . Kindly assigned it to me.

**Comment by yvkrishna** [comment] 2021-03-21 16:58
> @yvkrishna can i contribute to this isue under the label of gssoc'21

Up to now there are so many requests coming up for the same issue. Can you please work on other issues?

**Comment by yvkrishna** [comment] 2021-03-21 16:59
Dear Gssoc21 participants, You can start contributing, we will assign the members for the second round for the girl script summer of code. 😃

**Comment by iamansoni** [comment] 2021-03-29 04:34
Is this issue still needs to be addressed!
If yes, you can assign it to me!

**Comment by chebroluharika** [comment] 2021-03-30 08:00
@iamansoni yes, it was addresses as a part of https://github.com/flow2ml/Flow2ML/pull/21

**Comment by chebroluharika** [comment] 2021-03-30 08:02
@yvkrishna Please close this issue as it is a duplicate of https://github.com/flow2ml/Flow2ML/pull/21

**Comment by chebroluharika** [comment] 2021-03-31 07:46
Closing this as associated PR was merged.

**Closed by chebroluharika** 2021-03-31 07:46 UTC
Labels: gssoc21, level1
